# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  helloaspireapphost:
    image: helloaspireapphost
    build:
      context: .
      dockerfile: HelloAspire.AppHost/Dockerfile
    ports:
      - 5023:5023
